name: gwork_flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dart_jsonwebtoken: ^2.14.0
  shared_preferences: ^2.2.3
  image_picker: ^0.8.4+3
  permission_handler: ^10.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - lib/assets/template.jpeg
